component: flask
name: wb-backend
app: wb-backend
inputs:
  src:
    hook: pip3 install -r requirements.txt -t ./
    dist: ./
    exclude:
      - .env
  region: ap-guangzhou
  runtime: Python3.6
  apigatewayConf:
    protocols:
      - https
    environment: release
